### ISSUE TITLE
配置路由

### ISSUE THREAD

**Issue by bin9003** [yuminjustin/spotlight-cli#1]
// route
import Home from './page/home'
import News from './page/news'

import { router } from 'san-router'

router.add({rule: '/', Component: Home, target: '#app'});
router.add({rule: '/news', Component: News, target: '#app'});

// start
router.start()

配置路由后，不能访问其他路径，只能访问跟路径，我还需要配置什么？

**Comment by yuminjustin** [comment]
抱歉，sanjs我只在小项目中使用过，之前是做过demo（webpack按需加载方式）但没有运用到实际项目中→[查看](https://github.com/yuminjustin/san-sp-tpl-backups/blob/master/template/src/router.js)<br>
个人感觉sanjs是个大厂kpi的产物，各方面支持的都不好，所以不太建议放在比较大的项目，避免给自己挖坑涉及到【路由和支持低版本IE】的情况我还是比较保守的选择backbone。关于sanjs路由的问题你可以去@一下百度官方开发团队，希望他们还在运营这个框架。→[跳走](https://github.com/baidu/san-router)
